### ISSUE TITLE
Allow complete configuration from inventory.

### ISSUE THREAD

**Issue by joestewart** [brianshumate/ansible-hubot#5]
Hello,  Would you be interested in some changes to allow hubot configuration from inventory instead of some of it being in the role vars and templates?

I'll submit a PR for moving the vars to defaults first.
I have a series of other changes ready if this direction is acceptable.

thanks, Joe.

**Comment by brianshumate** [comment]
Hi Joe,

Thanks for the PR; I think it makes sense to do this, so I've merged it.

Cheers!
